### ISSUE TITLE
Run "nile node" cmd got this error

### ISSUE THREAD

**Issue by TheDAS-designer** [OpenZeppelin/nile#32] opened 2021-11-16 09:47 UTC
```
(env) xxxxx@xxxxxMacBook-Pro testProject % nile node
Traceback (most recent call last):
  File "/Users/xxxxx/devData/starkNet/testProject/env/bin/starknet-devnet", line 5, in <module>
    from starknet_devnet.server import main
  File "/Users/xxxxx/devData/starkNet/testProject/env/lib/python3.10/site-packages/starknet_devnet/server.py", line 3, in <module>
    from starkware.starknet.services.api.gateway.transaction import Deploy, InvokeFunction, Transaction
  File "/Users/xxxxx/devData/starkNet/testProject/env/lib/python3.10/site-packages/starkware/starknet/services/api/gateway/transaction.py", line 13, in <module>
    from services.everest.api.gateway.transaction import (
  File "/Users/xxxxx/devData/starkNet/testProject/env/lib/python3.10/site-packages/services/everest/api/gateway/transaction.py", line 5, in <module>
    from starkware.starkware_utils.validated_dataclass import ValidatedMarshmallowDataclass
  File "/Users/xxxxx/devData/starkNet/testProject/env/lib/python3.10/site-packages/starkware/starkware_utils/validated_dataclass.py", line 13, in <module>
    from starkware.starkware_utils.validated_fields import Field
  File "/Users/xxxxx/devData/starkNet/testProject/env/lib/python3.10/site-packages/starkware/starkware_utils/validated_fields.py", line 12, in <module>
    from starkware.starkware_utils.marshmallow_dataclass_fields import (
  File "/Users/xxxxx/devData/starkNet/testProject/env/lib/python3.10/site-packages/starkware/starkware_utils/marshmallow_dataclass_fields.py", line 6, in <module>
    from frozendict import frozendict
  File "/Users/xxxxx/devData/starkNet/testProject/env/lib/python3.10/site-packages/frozendict/__init__.py", line 16, in <module>
    class frozendict(collections.Mapping):
AttributeError: module 'collections' has no attribute 'Mapping'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/nile", line 8, in <module>
    sys.exit(cli())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/nile/main.py", line 122, in node
    node_command()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/nile/commands/node.py", line 8, in node_command
    subprocess.check_call("starknet-devnet")
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'starknet-devnet' returned non-zero exit status 1.
```

**Comment by fracek** [comment] 2021-11-16 10:33
It looks like the error is originating from starknet devnet? I see you're using Python 3.10, can you also post the version of starknet devnet, nile, cairo?

**Comment by TheDAS-designer** [comment] 2021-11-17 05:43
> It looks like the error is originating from starknet devnet? I see you're using Python 3.10, can you also post the version of starknet devnet, nile, cairo, and your OS?

OS: macOS 12.0.1
starknet-devnet:  0.1.5
cairo-lang:            0.5.2
cairo-nile :            0.2.1

**Comment by martriay** [comment] 2021-11-17 06:36
what happens if you run `starknet-devnet` standalone (but within env)?

**Comment by TheDAS-designer** [comment] 2021-11-17 09:37
> what happens if you run `starknet-devnet` standalone (but within env)?

(env)xxxx@xxxxdeMacBook-Pro testProject % starknet-devnet
Traceback (most recent call last):
  File "/Users/xxxx/devData/starkNet/testProject/env/bin/starknet-devnet", line 5, in <module>
    from starknet_devnet.server import main
  File "/Users/xxxx/devData/starkNet/testProject/env/lib/python3.10/site-packages/starknet_devnet/server.py", line 3, in <module>
    from starkware.starknet.services.api.gateway.transaction import Deploy, InvokeFunction, Transaction
  File "/Users/xxxx/devData/starkNet/testProject/env/lib/python3.10/site-packages/starkware/starknet/services/api/gateway/transaction.py", line 13, in <module>
    from services.everest.api.gateway.transaction import (
  File "/Users/xxxx/devData/starkNet/testProject/env/lib/python3.10/site-packages/services/everest/api/gateway/transaction.py", line 5, in <module>
    from starkware.starkware_utils.validated_dataclass import ValidatedMarshmallowDataclass
  File "/Users/xxxx/devData/starkNet/testProject/env/lib/python3.10/site-packages/starkware/starkware_utils/validated_dataclass.py", line 13, in <module>
    from starkware.starkware_utils.validated_fields import Field
  File "/Users/xxxx/devData/starkNet/testProject/env/lib/python3.10/site-packages/starkware/starkware_utils/validated_fields.py", line 12, in <module>
    from starkware.starkware_utils.marshmallow_dataclass_fields import (
  File "/Users/xxxx/devData/starkNet/testProject/env/lib/python3.10/site-packages/starkware/starkware_utils/marshmallow_dataclass_fields.py", line 6, in <module>
    from frozendict import frozendict
  File "/Users/xxxx/devData/starkNet/testProject/env/lib/python3.10/site-packages/frozendict/__init__.py", line 16, in <module>
    class frozendict(collections.Mapping):
AttributeError: module 'collections' has no attribute 'Mapping'

**Comment by fracek** [comment] 2021-11-17 14:25
It looks like the error is caused by `starknet-devnet`. I think their [repository](https://github.com/Shard-Labs/starknet-devnet/) is a better place for this issue.

**Comment by martriay** [comment] 2021-11-17 19:26
Indeed this seems to be a `starknet-devnet` specific issue. I'm closing this, feel free to open a new one if you deem it necessary.

**Closed by martriay** 2021-11-17 19:27 UTC
