### ISSUE TITLE
Cannot run nile using poetry

### ISSUE THREAD

**Issue by Pet3ris** [OpenZeppelin/nile#49] opened 2022-01-06 15:10 UTC
Trying to use nile from poetry in the following way:

```bash
poetry new nile-test # init new repo
cd nile-test
poetry add --dev cairo-nile # install nile
poetry run nile version
```

Resulting error is:

```
    from nile import __version__ as nile_version
ImportError: cannot import name '__version__' from 'nile' (unknown location)
```

Any idea for a workaround here? I'm trying to use `poetry` and `nile` together like `yarn` and `hardhat` are commonly used together in L1 land.

**Comment by fracek** [comment] 2022-01-06 15:39
Thanks for the report. I just tried to reproduce your problem but it's working as expected for me. What OS and Python version are you using? Have you tried creating a new virtual env?

```
(myenv) [fra@nixos:/tmp]$ poetry new nile-test
Created package nile_test in nile-test
(myenv) [fra@nixos:/tmp]$ cd nile-test/
(myenv) [fra@nixos:/tmp/nile-test]$ poetry add --dev cairo-nile
Using version ^0.3.0 for cairo-nile

Updating dependencies
Resolving dependencies... (3.6s)

Writing lock file

Package operations: 6 installs, 1 update, 0 removals

  • Installing attrs (21.4.0)
  • Installing more-itertools (8.12.0)
  • Updating packaging (20.9 -> 21.3)
  • Installing pluggy (0.13.1)
  • Installing py (1.11.0)
  • Installing wcwidth (0.2.5)
  • Installing pytest (5.4.3)
(myenv) [fra@nixos:/tmp/nile-test]$ poetry run nile
Usage: nile [OPTIONS] COMMAND [ARGS]...

  Nile CLI group.

Options:
  --help  Show this message and exit.

Commands:
  call         Call functions of StarkNet smart contracts.
  clean        Remove default build directory.
  compile      Compile cairo contracts.
  deploy       Deploy StarkNet smart contract.
  init         Nile CLI group.
  install      Install Cairo.
  invoke       Invoke functions of StarkNet smart contracts.
  node         Start StarkNet local network.
  raw-execute  Invoke a contract through an Account.
  send         Invoke a contract's method through an Account.
  setup        Do setup an Account contract.
  test         Run cairo test contracts.
  version      Print out toolchain version.
(myenv) [fra@nixos:/tmp/nile-test]$ poetry run nile version
0.3.0
(myenv) [fra@nixos:/tmp/nile-test]$
```

**Comment by Pet3ris** [comment] 2022-01-06 15:54
Thanks for the quick response!

Yeah nile works fine for me in a separate env but prefer using poetry to avoid having to switch envs between projects.

I'm using Python 3.8 in poetry, but will try again now with 3.7 as I've heard that works better with Cairo in general.

**Comment by fracek** [comment] 2022-01-09 15:21
I think we can close this issue since it seems unrelated to nile.

**Closed by fracek** 2022-01-09 15:21 UTC
